name: Lint
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]
    steps:
      - name: my-step
        run: poetry run flake8 brain_games
