name: Lint
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]
    steps:
      - name: Install dependencies
        run: |
          make install
          
      - name: Lint with flake8
        run: |
          make lint
